### ISSUE TITLE
Shield of Honor bug

### ISSUE THREAD

**Issue by Keldash** [XzeroAir/Trinkets-1.12.2#36]
Hello Xzero, I was making a Subject Science build along with Shield of Honor that way I don't need to worry about explosive visuals but for some reason the visual blurr is still going through even though I have the shield :( https://prnt.sc/s20g7j / https://prnt.sc/s20gsu <--- Initial hit causing blurr.

**Comment by XzeroAir** [comment]
due to how the blur effect from Enhanced Visuals works, It's shared between explosions, Entering/Exiting water, and a couple of other instances, so in order to keep it from breaking other effects, I have it only remove the blur when the value reaches a certain amount, so that is probably the reason it shows for a moment, this will be fixed in future updates

**Comment by Keldash** [comment]
You know I had a feeling that's what it was I just wanted to run it by you just in case something got through the works, I noticed when I took it off the blurr lasted a lot longer, but when it was on the blurr happened for a split moment then disappeared. I'l go ahead and remove the explosive visuals from my RLCraft for now. =) ty

**Comment by XzeroAir** [comment]
Should be fixed as of 0.30, but Requires Updating to 1.3.6+ of Enhanced Visuals, Which also requires updating Enhanced Visuals Dependencies
