### ISSUE TITLE
Config not disabling static mining properly

### ISSUE THREAD

**Issue by darkfirehunter** [XzeroAir/Trinkets-1.12.2#56]
**Describe the bug**

I have the tinkers construct mod so the static mining ability of the dwarf race is actually more of a deterrent than a boon so I attempted to disable it.  That is the only config option I  touched at first. Now onto the problem, after disabling static mining and using a pickaxe with a mining speed of 18 it will not break stone or other blocks with that hardness level, when I attempt to it shows them breaking but they just reappear. My next thought was that maybe something with either the attack or movement speed were doing it so I disabled those with the same effect. I even disabled skilled miner just to try that but no game. I have also deleted the config file to let it be recreated as well as uninstalled and reinstalled the mod. 

 - Version 30

**Comment by XzeroAir** [comment]
iirc, I think I did have a bug in version 0.30, where I didn't set up the config properly for it.
It is fixed in the latest 0.31 betas.
The Betas are near done, there are a couple of bugs with the Elf Charged shot and Tinkers/modded bows, and there are some Language/Naming stuff left, but they should be stable enough if you'd like to update.
I Appreciate the bug report.

**Comment by darkfirehunter** [comment]
I updated to the latest beta and the problem has resolved. Thanks for taking the time to answer.
