### ISSUE TITLE
Open GL Error with latest Trinkets mod. Never happened with older versions, only showed up with updated version.

### ISSUE THREAD

**Issue by ghost** [XzeroAir/Trinkets-1.12.2#60]
**Describe the bug**
Latest Trinkets causes OpenGL Errors when using the Betweenlands rowboat. I've had older versions of Trinkets installed for quite some time, and never had this error. Showed up as soon as I upgraded to the latest version `Trinkets and Baubles 0.31.4`

**Screenshots**
### [Video of the error:](https://streamable.com/zi7is8)

**Version (please complete the following information):**
 - Version Trinkets and Baubles 0.31.4

**Additional context**

**Comment by XzeroAir** [comment]
Which version did you use before?
I didn't change anything with rendering in 0.31.4.
and were you using any T&B Items while in the boat?

**Comment by ghost** [comment]
> which version did you use before?

Trinkets and Baubles-0.30.1

> were you using any T&B Items while in the boat?

Nope. This error occurs simply when the latest Trinkets version is installed, and while using the Betweenlands rowboat. Nothing else is required to trigger the error.

**Comment by ghost** [comment]
I can confirm this error still occurs with a modpack containing only:

Latest Trinkets 0.31.4
Optifine
Thebetweenlands

---

I can also confirm it **does** **not** occur with a modpack containing:

Trinkets 0.30.1
Optifine
Thebetweenlands

**Comment by XzeroAir** [comment]
Which version of Optifine? I'm not getting any errors in a new Minecraft instance with only T&B and the Betweenlands installed

**Comment by ghost** [comment]
[Optifine 1.12.2 HD_U_G5](https://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_G5.jar&x=b9f3), the latest official release for 1.12.2 Optifine.

**Comment by XzeroAir** [comment]
well, I'm getting the error now, absolutely no clue why it's happening at all, because Literally nothing should be rendering in the instances I tested, I'll continue to look into it, but unfortunately I have no solutions at the moment

**Comment by ghost** [comment]
Ok, keep me updated! It's not a game-breaking error, but certainly a nuisance. Let me know if you need me to do any testing before publishing.

**Comment by XzeroAir** [comment]
ok, So I Figured it out why it's showing the error now, and wasn't before, In the older versions I was only running some rendering code when the player was transformed, or transforming, I don't do that anymore because it shouldn't be necessary to do so, but for the sake of it, I re-added that check in my dev environment, If/when I do another update, it'll be included.

This doesn't actually fix the issue, and will still happen if you were to transform using any of the Race items.

I did a quick once over of the Betweenlands source, they're replacing the camera/entity renderer while the player is in the boat, theoretically, this should conflict with other mods that do just about any kind of rendering with the player, but I don't know enough about the Betweenlands and how they're rendering stuff to say for certain

Either way, there's not much I can do about this, sorry, I'll leave this open in case I figure something out, but for now, declaring this a Mod conflict

**Comment by ghost** [comment]
> theoretically, this should conflict with other mods that do just about any kind of rendering with the player

I'm also using a number of player-rendering mods besides Thebetweenlands, and **have** **been** for years, and have never had this issue. As soon as I updated Trinkets, issue is present.

> Either way, there's not much I can do about this, sorry... declaring this a Mod conflict

I mean... I have been using the older versions of Trinkets with this exact Betweenlands version just fine. You changed something in this updated version, and now there is a very real and breaking bug, caused by Trinkets. I don't really think that makes it a mod conflict, more of an issue on Trinket's side? 

I can understand how much effort bug fixing takes, and I would have to seem ungrateful or annoying, so I'd be happy to support any effort with a paypal or amazon giftcard, but I would hate for this bug to stay. I'm just about to [ship my modpack of almost 2 years of effort](https://www.youtube.com/watch?v=X8EpwHdR62k&ab_channel=Finecraft%3AEnhancedSurvival), and would love to not have this bug present.

**Comment by XzeroAir** [comment]
I don't mean to disregard the issue.
And you can probably even confirm this yourself using the older version of T&B, use any of the transformation rings, and then get in the boat, you should get the OpenGL error even in the older version, It just doesn't error when you're not transformed, because In the older version I was only calling the OpenGL methods when the player was transformed, or was transforming.

I've re-added that exact check in my dev environment, and I will include it in the next update, but what I'm saying is, The Betweenlands is doing some really weird rendering, that I might not be able to do anything about, I purposely left this issue open while I Look for a potential solution, but again, with what the Betweenlands is doing, I'm not sure if I can fix it.

**Comment by ghost** [comment]
> It just doesn't error when you're not transformed, because In the older version I was only calling the OpenGL methods when the player was transformed, or was transforming.

I'm not sure if it would matter at all, but in my latest config, I have indeed disabled any "Riding" actions while transformed as any of the races with: ` B:"07. Able to Mount Entities"=false`, meaning boat-riding is already impossible while transformed. If there was any way to do _this_: `In the older version I was only calling the OpenGL methods when the player was transformed` again, that would be an easy workaround.

I trust your judgement, and look forward to hearing more from you. And like I said I am happy to offer a little support if interested, just lmk your paypal.

**Comment by ghost** [comment]
Hi there, I don't want to bother you but I wanted to know if there was any chance of a fix or workaround for this! I'd really like to ship this modpack, and I've spent the last few months fixing bugs and working with mod authors to fix these bugs. This player-rendering bug is truly the last bug, after 6 months, in this pack. If not, that's ok, but I wanted to ask.
