### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by Sereath** [XzeroAir/Trinkets-1.12.2#61]
**Describe the bug**
Log being spammed by:
```
[Client thread/ERROR] [XAT]: Trinkets had an Error with Ability:lightning_bolt
```
```
[Client thread/INFO] [STDERR]: [xzeroair.trinkets.client.events.EventHandlerClient:clientTickEvent:157]: java.lang.NullPointerException
```
As long as my character has an Arcing Orb equipped, the log will keep repeating the same thing.

**Screenshots**
![image](https://user-images.githubusercontent.com/54506307/160077861-f8599e61-4ac5-4c68-8600-4318c4d40d0a.png)

**Version:**
 - 0.31.4

**Additional context**

log:
https://gist.github.com/Aeron216/0b24848ab3f081589f2e1f95050439d0

modlist:
https://gist.github.com/Aeron216/7a3f48e83cab04dce86a91166741a692

**Comment by XzeroAir** [comment]
Thanks for the Report, This has already come to my attention and fixed in my dev environment, I'm not sure When I'll push a new build, Working on 1.16 and another project.
It's an issue with the Arcing Orb's Lightning Bolt Ability, when I made a change in one of the latest updates, I apparently forgot to change a return value, resulting in a null pointer.
The Log Spam is because I Catch it before it causes a crash, It only happens if you have the Arcing orb equipped, and should only happen on a client, not on servers.
It shouldn't cause any issue other then being unable to use the Arcing Orbs Lightning bolt ability.

**Comment by USMP-lancer** [comment]
oh thats why i cant use its lightning

**Comment by XzeroAir** [comment]
I have a Beta/Release Candidate in my discord if you're interested.
otherwise, I should have a new version out on curseforge sometime in the week or so
