### ISSUE TITLE
Server crashes caused by race rings

### ISSUE THREAD

**Issue by 200542053** [XzeroAir/Trinkets-1.12.2#71]
**Describe the bug**
It seems that players wearing the race ring causes the server to crash, and the server will not restart and until the mod is removed or the mod version is downgraded.

There are so many players that I can't really figure out which ring is causing the crash.

This did not happen with the "Trinkets and Baubles-32-Pre-Release-Beta" version.

**Screenshots**

**Version (please complete the following information):**
 - Trinkets and Baubles-32-Pre-Release-Beta

**Additional context**
Forge: 14.23.5.2860
Server: [CatServer-222f2a5f-universal.jar](https://github.com/Luohuayu/CatServer/releases/download/23.02.08/CatServer-222f2a5f-universal.jar)
Crash-reports: 
[crash-2023-02-15_19.47.29-server.txt](https://github.com/XzeroAir/Trinkets/files/10754296/crash-2023-02-15_19.47.29-server.txt)

**Comment by XzeroAir** [comment]
If you turn off "Fix Effects when Changing Dimensions" in PotionCore's config, I think It'll fix the issue.
This is actually a compatibility issue with potion core, which is weird because I have potion core in my dev Environment and never experienced this, but I do have that config option disabled, so I guess it makes sense.

I Just added a check on my end that should solve this issue, It'll be included in the full version release sometime in a few days.
For now, Just turn that config in PotionCore off, and it should solve the crash.
